```{r km, cache=cacheon}

kmfunc <- function(time, event, eventname, cr = TRUE, yposplus = rep(0, 6), controls = TRUE) {
  if (cr) {
    if (controls) {
      data <- pdata
      groupcr <- data %>% pull(ef_casecontrol)
      ltymy <- c(1, 2, 1, 2, 1, 2)
      fitsn <- 1:6
    } else {
      data <- pdata %>% filter(casecontrol == "Case")
      groupcr <- data %>% pull(shf_ef_cat)
      yposplus <- yposplus[c(1, 3, 5)]
      ltymy <- c(1, 1, 1)
      fitsn <- 1:3
    }
    fit <- cuminc(
      ftime = data %>% pull(!!sym(time)),
      fstatus = data %>% pull(!!sym(event)),
      cencode = 0,
      group = groupcr
    )

    # c(bottom, left, top, right)
    par(mar = c(5, 4, 4, 7) + 0.1)

    plot(fit[fitsn],
      ylab = eventname,
      col = rep(global_kicols[c(1, 2, 3)], each = ifelse(controls, 2, 1)),
      wh = c(1110, 1110),
      xlim = c(0, 10 * 365),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = ltymy,
      xaxs = "i", yaxs = "i"
    )
  } else {
    fit <- survfit(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ shf_ef_cat + casecontrol")),
      data = pdata
    )
    # c(bottom, left, top, right)
    par(mar = c(5, 4, 4, 7) + 0.1)
    plots <- plot(fit,
      fun = "event",
      ylab = eventname,
      xscale = 365.25,
      yscale = 100,
      col = rep(global_kicols[c(1, 2, 3)], each = 2),
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 366 * 10),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = c(1, 2, 1, 2, 1, 2),
      xaxs = "i", yaxs = "i"
    )
  }

  axis(2, seq(0, 1, 0.25), seq(0, 100, 25), las = 2)
  axis(1, at = seq(0, 10, 2) * 365, seq(0, 10, 2))

  if (cr) {
    ypos <- timepoints(fit[fitsn], 365 * 10)$est
  } else {
    ypos <- 1 - summary(fit, 365 * 10, extend = TRUE)$surv
  }

  if (controls) {
    ytext <- paste0(rep(levels(pdata$shf_ef_cat), each = 2), " ", rep(levels(pdata$casecontrol), 3))
  }
  if (!controls) {
    ytext <- levels(pdata$shf_ef_cat)
  }

  ylabs <- bind_cols(ypos = ypos + yposplus, ytext = ytext)

  mtext(
    side = 4,
    line = .2,
    at = ylabs$ypos,
    ylabs$ytext,
    las = 1
  )
}
```


```{r mcf, cache=cacheon}

mcffunc <- function(datarec, eventname, yposplus = rep(0, 6), ymax = NULL, controls = TRUE) {
  if (controls) {
    fitscontrol <- mcf(Recur(sos_outtime, LopNcasecontrol, sos_out) ~ shf_ef_cat, data = datarec %>% filter(casecontrol == "Control"))
  }
  fitscase <- mcf(Recur(sos_outtime, LopNcasecontrol, sos_out) ~ shf_ef_cat, data = datarec %>% filter(casecontrol == "Case"))

  if (is.null(ymax)) {
    ymax <- ceiling(max(fitscase@MCF$MCF[fitscase@MCF$time <= 365 * 10]))
  }

  # c(bottom, left, top, right)
  par(mar = c(5, 4, 4, 7) + 0.1)

  plot(fitscase@MCF$time[fitscase@MCF$shf_ef_cat == "HFrEF"],
    fitscase@MCF$MCF[fitscase@MCF$shf_ef_cat == "HFrEF"],
    type = "l",
    ylab = eventname,
    col = global_kicols[1],
    xlim = c(0, 10 * 365),
    ylim = c(0, ymax),
    xlab = "Years",
    axes = F,
    lwd = 3,
    lty = 1,
    xaxs = "i", yaxs = "i"
  )

  lines(fitscase@MCF$time[fitscase@MCF$shf_ef_cat == "HFmrEF"],
    fitscase@MCF$MCF[fitscase@MCF$shf_ef_cat == "HFmrEF"],
    col = global_kicols[2],
    lwd = 3,
    lty = 1
  )

  lines(fitscase@MCF$time[fitscase@MCF$shf_ef_cat == "HFpEF"],
    fitscase@MCF$MCF[fitscase@MCF$shf_ef_cat == "HFpEF"],
    col = global_kicols[3],
    lwd = 3,
    lty = 1
  )

  if (controls) {
    lines(fitscontrol@MCF$time[fitscontrol@MCF$shf_ef_cat == "HFrEF"],
      fitscontrol@MCF$MCF[fitscontrol@MCF$shf_ef_cat == "HFrEF"],
      col = global_kicols[1],
      lwd = 3,
      lty = 2
    )

    lines(fitscontrol@MCF$time[fitscontrol@MCF$shf_ef_cat == "HFmrEF"],
      fitscontrol@MCF$MCF[fitscontrol@MCF$shf_ef_cat == "HFmrEF"],
      col = global_kicols[2],
      lwd = 3,
      lty = 2
    )

    lines(fitscontrol@MCF$time[fitscontrol@MCF$shf_ef_cat == "HFpEF"],
      fitscontrol@MCF$MCF[fitscontrol@MCF$shf_ef_cat == "HFpEF"],
      col = global_kicols[3],
      lwd = 3,
      lty = 2
    )
  }

  axis(2, seq(0, ymax, 1), seq(0, ymax, 1), las = 2)
  axis(1, at = seq(0, 10, 1) * 365, seq(0, 10, 1))

  # all no, all yes, no match
  ypos <- c(
    last(fitscase@MCF$MCF[fitscase@MCF$time <= 365 * 10 & fitscase@MCF$shf_ef_cat == "HFrEF"]),
    last(fitscase@MCF$MCF[fitscase@MCF$time <= 365 * 10 & fitscase@MCF$shf_ef_cat == "HFmrEF"]),
    last(fitscase@MCF$MCF[fitscase@MCF$time <= 365 * 10 & fitscase@MCF$shf_ef_cat == "HFpEF"])
  )
  if (controls) {
    ypos <- c(
      ypos[1],
      last(fitscontrol@MCF$MCF[fitscontrol@MCF$time <= 365 * 10 & fitscontrol@MCF$shf_ef_cat == "HFrEF"]),
      ypos[2],
      last(fitscontrol@MCF$MCF[fitscontrol@MCF$time <= 365 * 10 & fitscontrol@MCF$shf_ef_cat == "HFmrEF"]),
      ypos[3],
      last(fitscontrol@MCF$MCF[fitscontrol@MCF$time <= 365 * 10 & fitscontrol@MCF$shf_ef_cat == "HFpEF"])
    )
    ytext <- paste0(rep(levels(pdata$shf_ef_cat), each = 2), " ", rep(levels(pdata$casecontrol), 3))
  }
  if (!controls) {
    ytext <- levels(pdata$shf_ef_cat)
    yposplus <- yposplus[c(1, 3, 5)]
  }

  ylabs <- bind_cols(ypos = ypos + yposplus, ytext = ytext)

  mtext(
    side = 4,
    line = .2,
    at = ylabs$ypos,
    ylabs$ytext,
    las = 1
  )
}
```

```{r kmhosp, fig.cap="First all-cause hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospany",
  event = "sos_out_hospany_cr",
  eventname = "First all-cause hospitalization (%)",
  yposplus = c(-0.016, 0, 0, 0, 0.006, 0.003) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrechosp, fig.cap="Recurrent all-cause hospitalization", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pdata_rec_hospany,
  eventname = "Cumulative mean of all-cause hospitalizations",
  yposplus = c(0, -0.1, 0, 0, 0, 0.05) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmhfhosp, fig.cap="First HF hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hosphf",
  event = "sos_out_hosphf_cr",
  eventname = "First HF hospitalization (%)",
  controls = F,
  yposplus = c(0, 0, -0.01, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrechfhosp, fig.cap="Recurrent HF hospitalization", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pdata_rec_hosphf,
  eventname = "Cumulative mean of HF hospitalizations",
  controls = F,
  yposplus = c(0, 0, 0, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmcvhosp, fig.cap="First CV hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospcv",
  event = "sos_out_hospcv_cr",
  eventname = "First CV hospitalization (%)",
  yposplus = c(0.02, -0.02, -0.015, 0, 0, 0.02) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmreccvhosp, fig.cap="Recurrent CV hospitalization", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pdata_rec_hospcv,
  eventname = "Cumulative mean of CV hospitalizations",
  yposplus = c(-0.05, -0.08, 0, 0, 0.05, 0.08) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmnoncvhosp, fig.cap="First non-CV hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospnoncv",
  event = "sos_out_hospnoncv_cr",
  eventname = "First non-CV hospitalization (%)",
  yposplus = c(0, -0.005, 0, 0, 0, 0.005) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrecnoncvhosp, fig.cap="Recurrent non-CV hospitalization", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pdata_rec_hospnoncv,
  eventname = "Cumulative mean of non-CV hospitalizations",
  yposplus = c(0, 0, 0, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmhfvis, fig.cap="First out-patient visit", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_visany",
  event = "sos_out_visany_cr",
  eventname = "First out-patient visit (%)",
  yposplus = c(0.025, -0.005, 0.05, -0.03, 0.012, -0.05) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrechfvis, fig.cap="Recurrent out-patient visit", cache=cacheon, dependson="mcf"}
mcffunc(
  datarec = pdata_rec_visany,
  eventname = "Cumulative mean of out-patient visits",
  yposplus = c(0, -0.75, 0, 1.5, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmacdeath, fig.cap="All-cause mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_death",
  cr = FALSE,
  eventname = "All-cause mortality (%)",
  yposplus = c(-0.005, 0.0, 0.005, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmcvdeath, fig.cap="CV mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathcv_cr",
  eventname = "CV mortality (%)",
  yposplus = c(0, -0.01, -0.008, 0.008, 0.01, 0.01) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmnoncvdeath, fig.cap="Non-CV mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death",
  event = "sos_out_deathnoncv_cr",
  eventname = "Non-CV mortality (%)",
  yposplus = c(-0.02, -0.035, 0, -0.01, 0.03, 0.015) # case ref, control ref, case mref, control mref, case pef, control pef
)
```
