```{r kmhospefc, fig.cap="First all-cause hospitalization by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_hospany",
  event = "sos_out_hospany_cr",
  eventname = "First all-cause hospitalization (%)",
  yposplus = c(-0.016, 0, 0, 0, 0.006, 0.003) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrechospefc, fig.cap="Recurrent all-cause hospitalization by EF vs HF-free controls", cache=cacheon, dependson="mcffunc"}
mcffunc(
  data = pdata_rec_hospany,
  xvar = "ef_casecontrol",
  eventname = "Cumulative mean of all-cause hospitalizations",
  yposplus = c(0, -0.1, 0, 0, 0, 0.05) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmcvhospefc, fig.cap="First CV hospitalization by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_hospcv",
  event = "sos_out_hospcv_cr",
  eventname = "First CV hospitalization (%)",
  yposplus = c(0.02, -0.02, -0.015, 0, 0, 0.02) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmreccvhospefc, fig.cap="Recurrent CV hospitalization by EF vs HF-free controls", cache=cacheon, dependson="mcffunc"}
mcffunc(
  data = pdata_rec_hospcv,
  xvar = "ef_casecontrol",
  eventname = "Cumulative mean of CV hospitalizations",
  yposplus = c(-0.05, -0.08, 0, 0, 0.05, 0.08) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmnoncvhospefc, fig.cap="First non-CV hospitalization by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_hospnoncv",
  event = "sos_out_hospnoncv_cr",
  eventname = "First non-CV hospitalization (%)",
  yposplus = c(0, -0.005, 0, 0, 0, 0.005) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrecnoncvhospefc, fig.cap="Recurrent non-CV hospitalization by EF vs HF-free controls", cache=cacheon, dependson="mcffunc"}
mcffunc(
  data = pdata_rec_hospnoncv,
  xvar = "ef_casecontrol",
  eventname = "Cumulative mean of non-CV hospitalizations",
  yposplus = c(0, 0, 0, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmhfvisefc, fig.cap="First out-patient visit by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_visany",
  event = "sos_out_visany_cr",
  eventname = "First out-patient visit (%)",
  yposplus = c(0.025, -0.005, 0.05, -0.03, 0.012, -0.05) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmrechfvisefc, fig.cap="Recurrent out-patient visit by EF vs HF-free controls", cache=cacheon, dependson="mcffunc"}
mcffunc(
  data = pdata_rec_visany,
  xvar = "ef_casecontrol",
  eventname = "Cumulative mean of out-patient visits",
  yposplus = c(0, -0.75, 0, 1.5, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmacdeathefc, fig.cap="All-cause mortality by EF vs HF-free controls", cache=cacheon, dependson="kmfunc"}
kmfunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_death",
  event = "sos_out_death",
  eventname = "All-cause mortality (%)",
  yposplus = c(-0.005, 0.0, 0.005, 0, 0, 0) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmcvdeathefc, fig.cap="CV mortality by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_death",
  event = "sos_out_deathcv_cr",
  eventname = "CV mortality (%)",
  yposplus = c(0, -0.01, -0.008, 0.008, 0.01, 0.01) # case ref, control ref, case mref, control mref, case pef, control pef
)
```

```{r kmnoncvdeathefc, fig.cap="Non-CV mortality by EF vs HF-free controls", cache=cacheon, dependson="cifunc"}
cifunc(
  data = pdata,
  xvar = "ef_casecontrol",
  time = "sos_outtime_death",
  event = "sos_out_deathnoncv_cr",
  eventname = "Non-CV mortality (%)",
  yposplus = c(-0.02, -0.035, 0, -0.01, 0.03, 0.015) # case ref, control ref, case mref, control mref, case pef, control pef
)
```
